
export const  LOAD_REFRESHTOKENS = 'LOAD_REFRESH_TOKENS';
export const  LOAD_REFRESHTOKENS_SUCCESS = 'LOAD_REFRESH_TOKENS_SUCCESS';
export const  LOAD_REFRESHTOKENS_FAIL = 'LOAD_REFRESH_TOKENS_FAIL';

export const DELETE_REFRESHTOKEN = 'DELETE_REFRESHTOKEN';
export const DELETE_REFRESHTOKEN_SUCCESS = 'DELETE_REFRESHTOKEN_SUCCESS';
export const DELETE_REFRESHTOKEN_FAIL = 'DELETE_REFRESHTOKEN_FAIL';

export const loadRefreshTokens = () => ({ type: LOAD_REFRESHTOKENS });

export const deleteRefreshToken = (REFRESHToken) => ({ type: DELETE_REFRESHTOKEN, data: REFRESHToken });
